"""L2 exemption for auto-generated index docs (DECISIONS.md and similar).

Files containing an `Auto-generated` marker in the first 25 lines are
exempted from L2 metadata + required-section checks. Rationale: indexes
emitted by `cli.decisions_index` (or future generators) intentionally
lack the standard metadata block — they're machine-rendered overviews,
not authored docs.
"""

from __future__ import annotations

from pathlib import Path

from cli.lint import lint_doc


def _doc(tmp_path: Path, subdir: str, name: str, body: str) -> Path:
    p = tmp_path / "docs" / subdir / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body)
    return p


def test_auto_generated_decisions_index_exempted(tmp_path):
    body = (
        "# Architectural Decision Records — Index\n\n"
        "> Auto-generated by `design-docs decisions-index`. Do not edit by hand.\n\n"
        "**Total ADRs:** 1\n\n"
        "## By Status\n\n"
        "- [ADR-001](ADR-001-foo.md) — Implemented\n"
    )
    p = _doc(tmp_path, "adr", "DECISIONS.md", body)
    findings = lint_doc(p)
    assert findings == [], f"expected no findings on auto-generated index, got {[f.message for f in findings]}"


def test_regular_adr_still_validated(tmp_path):
    # Lacking metadata + sections — should still emit findings
    body = "# ADR-999 — Foo\n\n## Context\n\nbody\n"
    p = _doc(tmp_path, "adr", "ADR-999-foo.md", body)
    findings = lint_doc(p)
    assert findings, "expected metadata + section findings on regular adr"


def test_archive_path_exempted(tmp_path):
    """Archive is historical (= git history). L2 + L5 must not fire."""
    body = "# stale archived doc\n\n(no metadata block; no sections)\n"
    p = tmp_path / "docs" / "archive" / "design" / "stale.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body)
    findings = lint_doc(p)
    assert findings == [], f"archive must be exempt; got {[f.message for f in findings]}"


def test_archive_subtype_path_also_exempted(tmp_path):
    body = "# archived bug\n"
    p = tmp_path / "docs" / "archive" / "bugs" / "BUG-001-old.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body)
    findings = lint_doc(p)
    assert findings == []


def test_real_decisions_md_passes():
    """Smoke against the actual repo DECISIONS.md."""
    import subprocess
    repo_root = Path(subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True
    ).strip())
    p = repo_root / "docs" / "adr" / "DECISIONS.md"
    if not p.exists():
        return
    findings = lint_doc(p)
    assert findings == [], f"DECISIONS.md should pass L2 post-exemption, got {[f.message for f in findings]}"
