"""LLD-010 r4 — framework detection + --apply rollback + --verify.

Covers T1 (Slice 3.1), T3a-d (Slice 3.2), T4a-g (Slice 3.3),
T5a-h (Slice 3.4), T6a-d (Slice 3.5), T7a-b (Slice 3.6), T8 (Slice 3.7).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from unittest import mock

import pytest

from cli import install_hooks as ih
from cli.install_hooks import (
    EXPECTED_ENTRYPOINTS,
    FRAMEWORK_SNIPPET_PATH,
    ORCHESTRA_HOOK_IDS,
    PRECOMMIT_CONFIG,
    SKILL_TEMPLATES_DIR,
    UserConfigParseError,
    _detect_orchestra_ids,
    _emit_full_snippet,
    _is_precommit_framework,
    _orchestra_ids_state,
    _parse_user_config,
    install_via_framework_apply,
    install_via_framework_apply_with_rollback,
    main,
    verify_hooks_active,
)


# ============================================================================
# Slice 3.1 — snippet content (T1 + T2)
# ============================================================================


def test_t1_snippet_two_hook_ids_pass_filenames_false() -> None:
    import yaml
    snippet = yaml.safe_load(FRAMEWORK_SNIPPET_PATH.read_text())
    hooks = []
    for r in snippet.get("repos") or []:
        hooks.extend(r.get("hooks") or [])
    ids = {h["id"] for h in hooks}
    assert ids == {"orchestra-lint", "orchestra-commit-msg"}
    for h in hooks:
        assert h["pass_filenames"] is False, f"{h['id']} must have pass_filenames=False"


def test_t2_snippet_default_install_hook_types_directive() -> None:
    import yaml
    snippet = yaml.safe_load(FRAMEWORK_SNIPPET_PATH.read_text())
    types = snippet.get("default_install_hook_types")
    assert types == ["pre-commit", "commit-msg"]


# ============================================================================
# Slice 3.2 — framework detection helpers (T3a-d)
# ============================================================================


def _write_user_config(repo: Path, content: str) -> None:
    (repo / PRECOMMIT_CONFIG).write_text(content)


CONFIG_FULL = """repos:
  - repo: local
    hooks:
      - id: orchestra-lint
        entry: x
        language: system
        stages: [pre-commit]
      - id: orchestra-commit-msg
        entry: x
        language: system
        stages: [commit-msg]
"""

CONFIG_PARTIAL = """repos:
  - repo: local
    hooks:
      - id: orchestra-lint
        entry: x
        language: system
        stages: [pre-commit]
"""

CONFIG_NONE = """repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace
"""

CONFIG_MALFORMED = "repos: [\n  garbage: not yaml"


def test_t3a_full_config_returns_full_state(tmp_path: Path) -> None:
    _write_user_config(tmp_path, CONFIG_FULL)
    cfg = _parse_user_config(tmp_path)
    assert _orchestra_ids_state(cfg) == "full"


def test_t3b_none_state_emits_snippet(tmp_path: Path) -> None:
    _write_user_config(tmp_path, CONFIG_NONE)
    cfg = _parse_user_config(tmp_path)
    assert _orchestra_ids_state(cfg) == "none"
    snippet = _emit_full_snippet()
    assert "orchestra-lint" in snippet
    assert "orchestra-commit-msg" in snippet


def test_t3c_malformed_config_raises(tmp_path: Path) -> None:
    _write_user_config(tmp_path, CONFIG_MALFORMED)
    with pytest.raises(UserConfigParseError):
        _parse_user_config(tmp_path)


def test_t3d_partial_config_returns_partial(tmp_path: Path) -> None:
    _write_user_config(tmp_path, CONFIG_PARTIAL)
    cfg = _parse_user_config(tmp_path)
    assert _orchestra_ids_state(cfg) == "partial"
    # And install_via_framework_apply hard-fails
    rc = install_via_framework_apply(tmp_path)
    assert rc == 1


# ============================================================================
# Slice 3.3 — --verify hybrid fingerprint (T4a-g)
# ============================================================================


def _make_hook(repo: Path, name: str, content: str) -> Path:
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    p = hooks_dir / name
    p.write_text(content)
    p.chmod(0o755)
    return p


def test_t4a_raw_fingerprint_and_entrypoint_passes(tmp_repo: Path) -> None:
    _make_hook(tmp_repo, "pre-commit",
               "#!/usr/bin/env bash\n# orchestra raw hook\npython -m cli.lint --pre-commit\n")
    _make_hook(tmp_repo, "commit-msg",
               "#!/usr/bin/env bash\n# orchestra raw hook\npython -m cli.lint --commit-msg-finalize \"$1\"\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 0


def test_t4b_framework_fingerprint_passes(tmp_repo: Path) -> None:
    _make_hook(tmp_repo, "pre-commit",
               "#!/usr/bin/env bash\n# generated by pre-commit\nexec pre-commit hook-impl --config=.pre-commit-config.yaml --hook-stage pre-commit\n")
    _make_hook(tmp_repo, "commit-msg",
               "#!/usr/bin/env bash\n# generated by pre-commit\nexec pre-commit hook-impl --config=.pre-commit-config.yaml --hook-stage commit-msg\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 0


def test_t4c_commit_msg_missing_fails(tmp_repo: Path) -> None:
    _make_hook(tmp_repo, "pre-commit",
               "#!/usr/bin/env bash\n# orchestra\npython -m cli.lint --pre-commit\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 1


def test_t4d_pre_commit_missing_fails(tmp_repo: Path) -> None:
    _make_hook(tmp_repo, "commit-msg",
               "#!/usr/bin/env bash\n# orchestra\npython -m cli.lint --commit-msg-finalize \"$1\"\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 1


def test_t4e_no_fingerprint_fails(tmp_repo: Path) -> None:
    _make_hook(tmp_repo, "pre-commit", "#!/usr/bin/env bash\necho nothing\n")
    _make_hook(tmp_repo, "commit-msg", "#!/usr/bin/env bash\necho nothing\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 1


def test_t4f_fingerprint_at_line_8_plus_widened_scope(tmp_repo: Path) -> None:
    bulk_comments = "\n".join(f"# comment line {i}" for i in range(20))
    _make_hook(tmp_repo, "pre-commit",
               f"#!/usr/bin/env bash\n{bulk_comments}\n# orchestra\npython -m cli.lint --pre-commit\n")
    _make_hook(tmp_repo, "commit-msg",
               f"#!/usr/bin/env bash\n{bulk_comments}\n# orchestra\npython -m cli.lint --commit-msg-finalize \"$1\"\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 0


def test_t4g_substring_only_no_entrypoint_fails(tmp_repo: Path) -> None:
    """Stale-script false-PASS regression: orchestra comment but no entrypoint."""
    _make_hook(tmp_repo, "pre-commit",
               "#!/usr/bin/env bash\n# orchestra is great\necho hello\n")
    _make_hook(tmp_repo, "commit-msg",
               "#!/usr/bin/env bash\n# orchestra is great\necho hello\n")
    rc = verify_hooks_active(tmp_repo)
    assert rc == 1


# ============================================================================
# Slice 3.4 — --apply transactional rollback (T5a-h)
# ============================================================================


def test_t5a_apply_preserves_other_repos(tmp_repo: Path, monkeypatch) -> None:
    """Apply: orchestra entry appended; user's other repos preserved."""
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    monkeypatch.setattr(
        "cli.install_hooks.subprocess.run",
        lambda *a, **kw: subprocess.CompletedProcess(a, 0, "", ""),
    )
    monkeypatch.setattr("cli.install_hooks.verify_hooks_active", lambda r: 0)
    rc = install_via_framework_apply(tmp_repo)
    assert rc == 0
    import yaml
    after = yaml.safe_load(cfg_path.read_text())
    repos = after["repos"]
    # Original GitHub repo preserved
    assert any(r.get("repo", "").startswith("https://github.com/") for r in repos)
    # Orchestra local entry appended
    assert any(r.get("repo") == "local" for r in repos)


def test_t5b_apply_runs_pre_commit_install_both_types(tmp_repo: Path, monkeypatch) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    calls: list[list[str]] = []

    def fake_run(cmd, **kw):
        calls.append(cmd)
        return subprocess.CompletedProcess(cmd, 0, "", "")

    monkeypatch.setattr("cli.install_hooks.subprocess.run", fake_run)
    monkeypatch.setattr("cli.install_hooks.verify_hooks_active", lambda r: 0)
    install_via_framework_apply(tmp_repo)
    assert any("pre-commit" in c and "install" in c
               and "--hook-type" in c and "pre-commit" in c and "commit-msg" in c
               for c in calls)


def test_t5c_apply_post_install_verify_passes(tmp_repo: Path, monkeypatch) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    monkeypatch.setattr(
        "cli.install_hooks.subprocess.run",
        lambda *a, **kw: subprocess.CompletedProcess(a, 0, "", ""),
    )
    monkeypatch.setattr("cli.install_hooks.verify_hooks_active", lambda r: 0)
    rc = install_via_framework_apply(tmp_repo)
    assert rc == 0


def test_t5d_atomic_write_failure_preserves_user_config(tmp_repo: Path, monkeypatch) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    original = cfg_path.read_text()

    def fake_replace(src, dst):
        raise OSError("simulated atomic write failure")

    monkeypatch.setattr("cli.install_hooks.os.replace", fake_replace)
    rc = install_via_framework_apply(tmp_repo)
    assert rc == 1
    assert cfg_path.read_text() == original
    # tmp file cleaned up
    tmp = cfg_path.with_suffix(cfg_path.suffix + ".tmp")
    assert not tmp.exists()


def test_t5e_default_no_flag_print_only(tmp_repo: Path, capsys) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    original = cfg_path.read_text()
    rc = main(["--repo", str(tmp_repo)])
    assert rc == 0
    captured = capsys.readouterr()
    assert "framework_detected_print_only" in captured.err
    assert cfg_path.read_text() == original
    # No hooks raw-installed
    assert not (tmp_repo / ".git" / "hooks" / "pre-commit").exists()


def test_t5f_subprocess_stderr_surfaced_on_failure(tmp_repo: Path, monkeypatch, capsys) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    stderr_lines = "\n".join(f"err line {i}" for i in range(30))

    def fake_run(cmd, **kw):
        return subprocess.CompletedProcess(cmd, 1, "", stderr_lines)

    monkeypatch.setattr("cli.install_hooks.subprocess.run", fake_run)
    rc = install_via_framework_apply(tmp_repo)
    captured = capsys.readouterr()
    assert rc == 1
    # First 20 lines surfaced
    assert "err line 0" in captured.err
    assert "err line 19" in captured.err


def test_t5g_transactional_rollback_on_subprocess_fail(tmp_repo: Path, monkeypatch, capsys) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    original = cfg_path.read_text()

    def fake_run(cmd, **kw):
        return subprocess.CompletedProcess(cmd, 1, "", "fail")

    monkeypatch.setattr("cli.install_hooks.subprocess.run", fake_run)
    rc = install_via_framework_apply_with_rollback(tmp_repo)
    assert rc == 1
    assert cfg_path.read_text() == original
    captured = capsys.readouterr()
    assert "restored from backup" in captured.err
    # Backup cleaned
    backup = cfg_path.with_name(cfg_path.name + ".orchestra-backup")
    assert not backup.exists()


def test_t5h_transactional_rollback_on_verify_fail(tmp_repo: Path, monkeypatch) -> None:
    cfg_path = tmp_repo / PRECOMMIT_CONFIG
    cfg_path.write_text(CONFIG_NONE)
    original = cfg_path.read_text()

    monkeypatch.setattr(
        "cli.install_hooks.subprocess.run",
        lambda *a, **kw: subprocess.CompletedProcess(a, 0, "", ""),
    )
    monkeypatch.setattr("cli.install_hooks.verify_hooks_active", lambda r: 1)
    rc = install_via_framework_apply_with_rollback(tmp_repo)
    assert rc == 1
    assert cfg_path.read_text() == original


# ============================================================================
# Slice 3.5 — framework branch integration (T6a-d)
# ============================================================================


def test_t6a_no_framework_raw_install(tmp_repo: Path, monkeypatch) -> None:
    """T6a: no .pre-commit-config.yaml → raw install path (LLD-008)."""
    monkeypatch.setattr("sys.stdin.isatty", lambda: False)
    rc = main(["--all", "--repo", str(tmp_repo)])
    assert rc == 0
    assert (tmp_repo / ".git" / "hooks" / "pre-commit").exists()
    assert (tmp_repo / ".git" / "hooks" / "commit-msg").exists()


def test_t6b_framework_no_flags_print_only(tmp_repo: Path, capsys) -> None:
    (tmp_repo / PRECOMMIT_CONFIG).write_text(CONFIG_NONE)
    rc = main(["--repo", str(tmp_repo)])
    assert rc == 0
    captured = capsys.readouterr()
    assert "framework_detected_print_only" in captured.err
    assert not (tmp_repo / ".git" / "hooks" / "pre-commit").exists()


def test_t6c_framework_apply_auto_merge(tmp_repo: Path, monkeypatch) -> None:
    (tmp_repo / PRECOMMIT_CONFIG).write_text(CONFIG_NONE)
    monkeypatch.setattr(
        "cli.install_hooks.subprocess.run",
        lambda *a, **kw: subprocess.CompletedProcess(a, 0, "", ""),
    )
    monkeypatch.setattr("cli.install_hooks.verify_hooks_active", lambda r: 0)
    rc = main(["--apply", "--repo", str(tmp_repo)])
    assert rc == 0
    import yaml
    after = yaml.safe_load((tmp_repo / PRECOMMIT_CONFIG).read_text())
    assert any(r.get("repo") == "local" for r in after.get("repos") or [])


def test_t6d_framework_force_raw_bypasses_detection(tmp_repo: Path, monkeypatch) -> None:
    (tmp_repo / PRECOMMIT_CONFIG).write_text(CONFIG_NONE)
    monkeypatch.setattr("sys.stdin.isatty", lambda: False)
    rc = main(["--all", "--force-raw", "--repo", str(tmp_repo)])
    assert rc == 0
    assert (tmp_repo / ".git" / "hooks" / "pre-commit").exists()


# ============================================================================
# Slice 3.6 — hard-fail invariant (T7a-b)
# ============================================================================


def test_t7a_verify_fail_via_main_exits_non_zero(tmp_repo: Path) -> None:
    rc = main(["--verify", "--repo", str(tmp_repo)])
    assert rc == 1


def test_t7b_remediation_message_format(tmp_repo: Path, capsys) -> None:
    main(["--verify", "--repo", str(tmp_repo)])
    captured = capsys.readouterr()
    assert "pre-commit install --hook-type" in captured.err


# ============================================================================
# Slice 3.7 — template-ownership invariant (T8)
# ============================================================================


def test_t8_template_ownership_files_exist() -> None:
    cli_templates_path = (Path(__file__).resolve().parent.parent
                          / "cli/templates/precommit-yaml-patch.txt")
    skill_snippet_path = FRAMEWORK_SNIPPET_PATH
    assert cli_templates_path.is_file()
    assert skill_snippet_path.is_file()
    # Both files have header comments documenting placement rule
    cli_text = cli_templates_path.read_text()
    skill_text = skill_snippet_path.read_text()
    # skill snippet header mentions placement rule + LLD-010 A8
    assert "skills/commit/templates" in skill_text or "LLD-010" in skill_text
