"""Install orchestra git hooks into .git/hooks/.

Idempotent. Detects existing hook → diff + prompt (default skip).
With --force: replace unconditionally. With --on-conflict=<skip|replace|append>:
non-interactive (honored verbatim; --force precedence).

Usage:
    python -m cli.install_hooks                       # pre-commit only
    python -m cli.install_hooks --commit-msg          # commit-msg only
    python -m cli.install_hooks --all                 # both
    python -m cli.install_hooks --force               # replace existing
    python -m cli.install_hooks --on-conflict=skip    # non-interactive skip
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

SKILL_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "skills" / "commit" / "templates"

HOOK_TEMPLATES = {
    "pre-commit": SKILL_TEMPLATES_DIR / "pre-commit.sh",
    "commit-msg": SKILL_TEMPLATES_DIR / "commit-msg.sh",
}

# v1.7 LLD-010 r4 — framework detection
PRECOMMIT_CONFIG = ".pre-commit-config.yaml"
FRAMEWORK_SNIPPET_PATH = SKILL_TEMPLATES_DIR / "precommit-framework-snippet.yaml"
ORCHESTRA_HOOK_IDS = frozenset({"orchestra-lint", "orchestra-commit-msg"})

RAW_FINGERPRINT = "orchestra"
FRAMEWORK_FINGERPRINT = "generated by pre-commit"
EXPECTED_ENTRYPOINTS = {
    "pre-commit": [
        "python -m cli.lint --pre-commit",
        "pre-commit hook-impl",
        "pre-commit run",
    ],
    "commit-msg": [
        "python -m cli.lint --commit-msg-finalize",
        "pre-commit hook-impl",
    ],
}


class SecurityError(Exception):
    """Raised when hook destination fails symlink/containment safety check."""


class UserConfigParseError(Exception):
    """Raised when .pre-commit-config.yaml is present but YAML is malformed."""


def _verify_hook_destination_safe(hook_path: Path, repo_root: Path) -> None:
    """Reject symlinked destinations + parent dirs outside repo boundary.

    Per LLD-008 r7 Security § + codex r4 high #2: `.git/hooks/<hook>` could
    itself be a symlink pointing outside the repo. Fail-closed before any write.
    """
    if hook_path.is_symlink():
        raise SecurityError(
            f"refusing to write to symlinked hook destination: "
            f"{hook_path} -> {hook_path.readlink()}. Remove the symlink and retry."
        )
    resolved_parent = hook_path.parent.resolve()
    resolved_repo = repo_root.resolve()
    if not str(resolved_parent).startswith(str(resolved_repo)):
        raise SecurityError(
            f"hook destination outside repo boundary: {resolved_parent}"
        )


def install_one_hook(
    repo_root: Path,
    hook_name: str,
    force: bool = False,
    on_conflict: str | None = None,
    input_fn=input,
) -> int:
    """Install a single git hook. Returns 0 on success, non-zero on error.

    `on_conflict`: None (argparse sentinel — TTY fallback to prompt, non-TTY to
    skip), or one of {skip, replace, append} (honored verbatim, non-interactive).
    `force` takes precedence: when True, replaces unconditionally regardless of
    on_conflict.
    """
    git_dir = repo_root / ".git"
    if not git_dir.is_dir():
        print(f"error: {repo_root} is not a git repo (no .git/ found)", file=sys.stderr)
        return 1

    template_path = HOOK_TEMPLATES.get(hook_name)
    if template_path is None:
        print(f"error: unknown hook {hook_name!r}", file=sys.stderr)
        return 1

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_path = hooks_dir / hook_name

    _verify_hook_destination_safe(hook_path, repo_root)

    expected_content = template_path.read_text()

    if hook_path.exists() and not force:
        existing = hook_path.read_text()
        if existing == expected_content:
            print(f"orchestra {hook_name} hook already installed at {hook_path}")
            return 0

        # Resolve on_conflict sentinel: None → TTY fallback
        resolved = on_conflict
        if resolved is None:
            if sys.stdin.isatty():
                print(
                    f"existing {hook_name} hook at {hook_path} differs from "
                    f"orchestra hook.",
                    file=sys.stderr,
                )
                print(
                    "Choose: [a]ppend orchestra hook, [r]eplace, [s]kip (default skip):",
                    file=sys.stderr,
                )
                choice = input_fn("> ").strip().lower()
                resolved = {"a": "append", "r": "replace", "s": "skip"}.get(
                    choice, "skip"
                )
            else:
                resolved = "skip"

        if resolved == "skip":
            print(f"skipped {hook_path}", file=sys.stderr)
            return 0
        if resolved == "replace":
            shutil.copy(template_path, hook_path)
            os.chmod(hook_path, 0o755)
            print(f"replaced {hook_path}")
            return 0
        if resolved == "append":
            existing_no_shebang = existing
            if existing.startswith("#!"):
                existing_no_shebang = "\n".join(existing.split("\n")[1:])
            new_content = (
                expected_content.rstrip()
                + "\n\n# Original hook content (preserved):\n"
                + existing_no_shebang
            )
            hook_path.write_text(new_content)
            os.chmod(hook_path, 0o755)
            print(f"appended to {hook_path}")
            return 0
        # Should be unreachable (argparse choices restrict)
        print(f"error: unknown on_conflict value: {resolved!r}", file=sys.stderr)
        return 1

    # New install OR force=True path
    shutil.copy(template_path, hook_path)
    os.chmod(hook_path, 0o755)
    if force and hook_path.exists():
        print(f"installed orchestra {hook_name} hook at {hook_path}")
    else:
        print(f"installed orchestra {hook_name} hook at {hook_path}")
    return 0


# Backward-compat alias for v1.1 callers + tests
def install_hook(repo_root: Path, force: bool = False, input_fn=input) -> int:
    """v1.1 entry point — installs pre-commit only. Preserved for compatibility."""
    return install_one_hook(repo_root, "pre-commit", force=force, input_fn=input_fn)


# ---------------------------------------------------------------------------
# v1.7 LLD-010 r4 — Framework detection + --verify + --apply
# ---------------------------------------------------------------------------


def _is_precommit_framework(repo_root: Path) -> bool:
    return (repo_root / PRECOMMIT_CONFIG).exists()


def _parse_user_config(repo_root: Path) -> dict:
    """Parse user .pre-commit-config.yaml; raise UserConfigParseError on parse error."""
    import yaml as _yaml
    cfg_path = repo_root / PRECOMMIT_CONFIG
    if not cfg_path.exists():
        return {}
    try:
        data = _yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    except _yaml.YAMLError as e:
        raise UserConfigParseError(
            f"user .pre-commit-config.yaml malformed: {e}. "
            f"Fix YAML syntax then retry, or use --force-raw to skip framework path."
        )
    return data or {}


def _detect_orchestra_ids(user_cfg: dict) -> set[str]:
    found: set[str] = set()
    for repo in user_cfg.get("repos") or []:
        if (repo.get("repo") or "") != "local":
            continue
        for h in (repo.get("hooks") or []):
            hid = h.get("id")
            if hid in ORCHESTRA_HOOK_IDS:
                found.add(hid)
    return found


def _orchestra_ids_state(user_cfg: dict) -> str:
    """Return 'none', 'partial', or 'full'."""
    found = _detect_orchestra_ids(user_cfg)
    if not found:
        return "none"
    if found == ORCHESTRA_HOOK_IDS:
        return "full"
    return "partial"


def _emit_full_snippet() -> str:
    return FRAMEWORK_SNIPPET_PATH.read_text(encoding="utf-8")


def verify_hooks_active(repo_root: Path) -> int:
    """Hybrid verify: substring fingerprint floor + entrypoint pattern assertion.

    Per LLD-010 r4 A4 + codex r2 HIGH#4: substring alone catches missing-hook;
    entrypoint pattern catches stale orchestra-comment-only scripts (false-PASS surface).
    """
    findings: list[str] = []
    for hook_name in ("pre-commit", "commit-msg"):
        hook_path = repo_root / ".git" / "hooks" / hook_name
        if not hook_path.exists():
            findings.append(f"{hook_name}: missing at {hook_path}")
            continue
        content = hook_path.read_text(encoding="utf-8", errors="replace")
        content_lower = content.lower()
        if (RAW_FINGERPRINT.lower() not in content_lower
                and FRAMEWORK_FINGERPRINT.lower() not in content_lower):
            findings.append(
                f"{hook_name}: present but no orchestra/framework fingerprint found"
            )
            continue
        expected_any = EXPECTED_ENTRYPOINTS[hook_name]
        if not any(pattern in content for pattern in expected_any):
            findings.append(
                f"{hook_name}: fingerprint present but no expected entrypoint pattern "
                f"found. Expected one of: {expected_any}."
            )
    if findings:
        print("FAIL — hook verification failed:", file=sys.stderr)
        for f in findings:
            print(f"  - {f}", file=sys.stderr)
        print(file=sys.stderr)
        print("Remediation: pre-commit install --hook-type pre-commit "
              "--hook-type commit-msg", file=sys.stderr)
        print("If issue persists: file BUG with output of `pre-commit --version` "
              "and .pre-commit-config.yaml excerpt.", file=sys.stderr)
        return 1
    print("PASS — both pre-commit and commit-msg hooks active", file=sys.stderr)
    return 0


def install_via_framework_apply(repo_root: Path) -> int:
    """Auto-merge orchestra entries + run pre-commit install + verify."""
    import yaml as _yaml
    try:
        user_cfg = _parse_user_config(repo_root)
    except UserConfigParseError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    state = _orchestra_ids_state(user_cfg)
    if state == "full":
        print("orchestra hooks already configured in .pre-commit-config.yaml; "
              "running --verify", file=sys.stderr)
        return verify_hooks_active(repo_root)
    if state == "partial":
        found = _detect_orchestra_ids(user_cfg)
        missing = ORCHESTRA_HOOK_IDS - found
        print(
            f"error: partial orchestra config detected: {sorted(found)} present; "
            f"{sorted(missing)} absent. Manual merge required to avoid duplicate-id "
            f"collision, or re-run with --force-raw to skip framework path entirely.",
            file=sys.stderr,
        )
        return 1

    snippet = _yaml.safe_load(FRAMEWORK_SNIPPET_PATH.read_text(encoding="utf-8")) or {}
    user_cfg.setdefault("repos", []).extend(snippet.get("repos") or [])
    types = user_cfg.get("default_install_hook_types") or []
    for required in ("pre-commit", "commit-msg"):
        if required not in types:
            types.append(required)
    user_cfg["default_install_hook_types"] = types

    cfg_path = repo_root / PRECOMMIT_CONFIG
    tmp = cfg_path.with_suffix(cfg_path.suffix + ".tmp")
    try:
        with tmp.open("w", encoding="utf-8") as f:
            f.write(_yaml.safe_dump(user_cfg, sort_keys=False, default_flow_style=False))
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, cfg_path)
        dir_fd = os.open(str(cfg_path.parent), os.O_RDONLY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    except OSError as e:
        if tmp.exists():
            tmp.unlink(missing_ok=True)
        print(f"error: atomic write of {cfg_path} failed: {e}", file=sys.stderr)
        return 1

    result = subprocess.run(
        ["pre-commit", "install", "--hook-type", "pre-commit", "--hook-type", "commit-msg"],
        cwd=repo_root, capture_output=True, text=True,
    )
    if result.returncode != 0:
        stderr_head = "\n".join(result.stderr.splitlines()[:20])
        print(
            f"error: pre-commit install failed (rc={result.returncode}).\n"
            f"--- pre-commit stderr (first 20 lines) ---\n{stderr_head}\n"
            f"Remediation: ensure pre-commit >=3.0 installed (`pip install pre-commit`); "
            f"re-run with --force-raw to skip framework path.",
            file=sys.stderr,
        )
        return result.returncode

    return verify_hooks_active(repo_root)


def install_via_framework_apply_with_rollback(repo_root: Path) -> int:
    """Transactional wrapper: snapshot config; restore on failure."""
    cfg_path = repo_root / PRECOMMIT_CONFIG
    backup_path = cfg_path.with_name(cfg_path.name + ".orchestra-backup")
    new_install_sentinel = "__ORCHESTRA_NEW_INSTALL__"

    if cfg_path.exists():
        backup_path.write_bytes(cfg_path.read_bytes())
    else:
        backup_path.write_text(new_install_sentinel)

    def _rollback(reason: str) -> int:
        try:
            backup_content = backup_path.read_text(errors="replace")
        except OSError:
            backup_content = ""
        if backup_content == new_install_sentinel:
            cfg_path.unlink(missing_ok=True)
        else:
            try:
                os.replace(backup_path, cfg_path)
            except OSError:
                pass
        backup_path.unlink(missing_ok=True)
        print(f"error: {reason}. Original .pre-commit-config.yaml restored from "
              f"backup.", file=sys.stderr)
        return 1

    try:
        rc = install_via_framework_apply(repo_root)
    except Exception as e:
        return _rollback(f"exception during apply: {e}")
    if rc != 0:
        return _rollback(f"--apply failed (rc={rc})")

    backup_path.unlink(missing_ok=True)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="orchestra install-hooks")
    parser.add_argument(
        "--commit-msg",
        action="store_true",
        help="Install commit-msg hook (Refs: line check at message author time)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Install both pre-commit and commit-msg hooks",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace existing hook unconditionally (precedence over --on-conflict)",
    )
    parser.add_argument(
        "--on-conflict",
        choices=["skip", "replace", "append"],
        default=None,
        help="Conflict resolution when existing hook differs; default: interactive if TTY else skip",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Framework mode: auto-merge orchestra entries into .pre-commit-config.yaml + run pre-commit install + verify",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify both pre-commit and commit-msg hooks present + contain orchestra fingerprint",
    )
    parser.add_argument(
        "--force-raw",
        action="store_true",
        help="Bypass framework detection; install raw hooks even if .pre-commit-config.yaml present",
    )
    parser.add_argument("--repo", default=".", help="Repo root (default: cwd)")
    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve()

    if args.verify:
        return verify_hooks_active(repo)

    # Framework detection branch (per LLD-010 r4 A6)
    if _is_precommit_framework(repo) and not args.force_raw:
        if args.apply:
            return install_via_framework_apply_with_rollback(repo)
        print("framework_detected_print_only: .pre-commit-config.yaml present.",
              file=sys.stderr)
        print("Append the following snippet to your .pre-commit-config.yaml "
              "(or re-run with --apply for auto-merge):", file=sys.stderr)
        print(file=sys.stderr)
        print(_emit_full_snippet())
        print(file=sys.stderr)
        print("Then run: pre-commit install --hook-type pre-commit --hook-type commit-msg",
              file=sys.stderr)
        return 0

    kwargs = {"force": args.force, "on_conflict": args.on_conflict}

    if args.all:
        rc1 = install_one_hook(repo, "pre-commit", **kwargs)
        rc2 = install_one_hook(repo, "commit-msg", **kwargs)
        return rc1 or rc2
    if args.commit_msg:
        return install_one_hook(repo, "commit-msg", **kwargs)
    return install_one_hook(repo, "pre-commit", **kwargs)


if __name__ == "__main__":
    sys.exit(main())
