"""design-docs decisions-index — auto-generate docs/adr/DECISIONS.md.

Walks the ADR directory, extracts metadata + relationship types
(Supersedes / Superseded by / Related), and emits a searchable index.

Usage:
    python -m design_docs.decisions_index --adr-dir docs/adr/ --output docs/adr/DECISIONS.md

Run as a post-commit hook to keep the index fresh, or via GitHub Action.

The relationship graph is derived from the "Related Documents" section
of each ADR. Lines like:
    - Supersedes: ADR-003-old-decision
    - Superseded by: ADR-014-new-decision
    - Related: ADR-002-other, ADR-005-context
become bidirectional edges in the output.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ADR_FILENAME_RE = re.compile(r"^ADR-(\d{3})-([a-z0-9-]+)\.md$")
TITLE_RE = re.compile(r"^#\s+(ADR-\d{3}:.+)$", re.MULTILINE)
META_RE = re.compile(r"^>\s+\*\*([^:*]+):\*\*\s+(.+)$", re.MULTILINE)
SUPERSEDES_RE = re.compile(r"-\s*Supersedes:\s*(ADR-\d{3}[^\s,]*)", re.IGNORECASE)
SUPERSEDED_BY_RE = re.compile(r"-\s*Superseded\s*by:\s*(ADR-\d{3}[^\s,]*)", re.IGNORECASE)
RELATED_RE = re.compile(r"-\s*Related:\s*(.+)", re.IGNORECASE)


@dataclass
class ADRRecord:
    number: int
    slug: str
    path: Path
    title: str = ""
    status: str = ""
    date: str = ""
    dri: str = ""
    supersedes: list[str] = field(default_factory=list)
    superseded_by: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)


def parse_adr(path: Path) -> ADRRecord | None:
    match = ADR_FILENAME_RE.match(path.name)
    if not match:
        return None

    record = ADRRecord(
        number=int(match.group(1)),
        slug=match.group(2),
        path=path,
    )
    text = path.read_text(encoding="utf-8")

    title_match = TITLE_RE.search(text)
    if title_match:
        record.title = title_match.group(1).strip()

    metadata = dict((k.strip(), v.strip()) for k, v in META_RE.findall(text[:1500]))
    record.status = metadata.get("Status", "").split("|")[0].strip()
    record.date = metadata.get("Date", "")
    record.dri = metadata.get("DRI", "")

    for ref in SUPERSEDES_RE.findall(text):
        ref_clean = ref.split("-")[0] + "-" + ref.split("-")[1]  # ADR-NNN
        if ref_clean.startswith("ADR-"):
            record.supersedes.append(ref_clean)
    for ref in SUPERSEDED_BY_RE.findall(text):
        ref_clean = ref.split("-")[0] + "-" + ref.split("-")[1]
        if ref_clean.startswith("ADR-"):
            record.superseded_by.append(ref_clean)
    for related_line in RELATED_RE.findall(text):
        for ref in re.findall(r"ADR-\d{3}", related_line):
            if ref not in record.related:
                record.related.append(ref)

    return record


def collect_adrs(adr_dir: Path) -> list[ADRRecord]:
    records: list[ADRRecord] = []
    for path in sorted(adr_dir.glob("ADR-*.md")):
        record = parse_adr(path)
        if record:
            records.append(record)
    records.sort(key=lambda r: r.number)
    return records


def render_index(records: list[ADRRecord]) -> str:
    lines: list[str] = []
    lines.append("# Architectural Decision Records — Index")
    lines.append("")
    lines.append("> Auto-generated by `design-docs decisions-index`. Do not edit by hand.")
    lines.append("")
    lines.append(f"**Total ADRs:** {len(records)}")
    lines.append("")
    lines.append("## By Status")
    lines.append("")

    status_groups: dict[str, list[ADRRecord]] = {}
    for rec in records:
        status_groups.setdefault(rec.status or "Unknown", []).append(rec)
    for status in ["Approved", "Implemented", "Proposed", "Draft", "Superseded", "Rejected", "Unknown"]:
        if status not in status_groups:
            continue
        lines.append(f"### {status}")
        lines.append("")
        for rec in status_groups[status]:
            lines.append(f"- [{rec.title}]({rec.path.name}) — {rec.date}")
        lines.append("")

    lines.append("## All ADRs")
    lines.append("")
    lines.append("| # | Title | Status | Date | Relationships |")
    lines.append("|---|-------|--------|------|---------------|")
    for rec in records:
        rels = []
        if rec.supersedes:
            rels.append(f"⬆ {', '.join(rec.supersedes)}")
        if rec.superseded_by:
            rels.append(f"⬇ {', '.join(rec.superseded_by)}")
        if rec.related:
            rels.append(f"↔ {', '.join(rec.related)}")
        rel_str = " · ".join(rels) if rels else "—"
        lines.append(f"| {rec.number:03d} | [{rec.title}]({rec.path.name}) | {rec.status or '?'} | {rec.date or '?'} | {rel_str} |")
    lines.append("")
    lines.append("Legend: ⬆ supersedes · ⬇ superseded by · ↔ related")
    lines.append("")

    # Detect inconsistent supersession links
    by_id = {f"ADR-{r.number:03d}": r for r in records}
    issues: list[str] = []
    for rec in records:
        rec_id = f"ADR-{rec.number:03d}"
        for sup in rec.supersedes:
            other = by_id.get(sup)
            if other and rec_id not in other.superseded_by:
                issues.append(
                    f"- {rec_id} claims `Supersedes: {sup}`, but {sup} does not have "
                    f"`Superseded by: {rec_id}` — supersession links must be bidirectional."
                )
        for sup_by in rec.superseded_by:
            other = by_id.get(sup_by)
            if other and rec_id not in other.supersedes:
                issues.append(
                    f"- {rec_id} claims `Superseded by: {sup_by}`, but {sup_by} does not have "
                    f"`Supersedes: {rec_id}`."
                )
    if issues:
        lines.append("## ⚠ Consistency Warnings")
        lines.append("")
        lines.extend(issues)
        lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="design-docs decisions-index")
    parser.add_argument("--adr-dir", default="docs/adr/", help="ADR directory (default: docs/adr/)")
    parser.add_argument("--output", default="docs/adr/DECISIONS.md", help="Output index path")
    args = parser.parse_args(argv)

    adr_dir = Path(args.adr_dir).resolve()
    if not adr_dir.is_dir():
        print(f"error: {adr_dir} is not a directory", file=sys.stderr)
        return 2

    records = collect_adrs(adr_dir)
    if not records:
        print(f"error: no ADRs found in {adr_dir}", file=sys.stderr)
        return 1

    output = Path(args.output).resolve()
    output.write_text(render_index(records), encoding="utf-8")
    print(f"wrote {output} ({len(records)} ADRs indexed)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
